### ISSUE TITLE
Contribute back to Huginn?

### ISSUE THREAD

**Issue by cantino** [automaticmode/active_workflow#2]
Hey folks, this looks like an awesome fork of Huginn, with some nice API additions. What made you decide not to contribute back upstream?

**Comment by cantino** [comment]
Thanks @vidas. That's of course completely fine with our open source license. You can do whatever you'd like with the code. That said, are you open to contributing some of the API improvements upstream?

**Comment by virtadpt** [comment]
Like the Remote Agents code, perhaps?  Please?

**Comment by vidas** [comment]
We are definitely open to contributing upstream.

REST(ish) API feature, for example, can be quite easily ported to Huginn.

Remote Agent API is very different though. It assumes a simplified Agent model.
If ported to Huginn as is, remote agents would become third-class citizens.
Remote agents have no Liquid templating, no File support, can't be
"long-running" agents. They talk to other agents *exclusively* through messages
(which is not the case with Huginn). Some of these features will come back
but in a very different and incompatible way. ActiveWorkflow can afford to have
breaking changes at this stage, but I don't think this would be an
appropriate solution for Huginn.

Why not create a Huginn issue to discuss how and what could be done with
regards to remote agents? We should definitely strive to have at least some
compatibility where possible.
