### ISSUE TITLE
Updating Remote Agent information/description

### ISSUE THREAD

**Issue by suhrm1** [automaticmode/active_workflow#8]
Hey,
I noticed that when updating a Remote Agent's description, the AW main application does not pull updated name, description, etc. Is it possible to manually trigger an update, clearing caches or something?

Best regards,
Markus

**Comment by vidas** [comment]
Hi Markus!

Unfortunately, whenever you update _meta_ information of a remote agent (whatever `register` method returns) you have to restart ActiveWorkflow. Right now remote agents are mirrored by "proxy classes" that are created during ActiveWorkflow startup. Until we reimplement all core agents using the same remote agent API this will be the case... I hope this helps.

Thank you!
Vidas

P.S. You can update your `check`/`receive` methods whenever you want though. It will just work - very useful when implementing/debugging agents.

**Comment by suhrm1** [comment]
Ah thank you, I somehow was under the impression that restarting ActiveWorkflow did not trigger an update of meta information.

Quick related question: is it possible to provide `message_description` for Remove Agents? I tried just returning markdown under that key with the `register` method but it did not seem to be processed by ActiveWorkflow.

**Comment by vidas** [comment]
`message_description` property is not yet implemented for remote agents. It would not be very useful to make it a static constant, it should represent a real message format (that can change depending on agents configuration) therefore can't be done at the registration stage. This and other features will be added to the Remote Agent API while migrating core agents to it.

For now, I suggest describing the message format in the general description.

Thanks for your interest!

Vidas

**Comment by suhrm1** [comment]
Thank you again for clarifying. I'm looking forward to upcoming developments.

Kind regards,
Markus
